
name: fahleh_plus_beta
description: نسخه آزمایشی اپلیکیشن فحله پلاس
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

flutter:
  uses-material-design: true
